apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dkan2
  name: dkan2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkan2
  template:
    metadata:
      labels:
        app: dkan2
    spec:
      initContainers:
        - name: init-code
          image: markaspot/dkan2:latest
          imagePullSecrets:
            - name: regcred
          volumeMounts:
            - mountPath: /var/www/html
              name: drupal-data
          command: ["/bin/sh", "-c", "cp -r /app/data/. /var/www/html"]
      containers:
        - name: nginx
          image: nginx:stable-alpine
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c",  "" ]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: drupal-data
              mountPath: /var/www/html
            - name: drupal-data-files
              mountPath: /app/data/docroot/sites/default/files
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: drupal
          imagePullPolicy: Always
          image: markaspot/dkan2:latest
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c",  "chown -R www-data:www-data /var/www/html && ./install.sh && cp -r /app/data/. /var/www/html" ]
          volumeMounts:
            - name: drupal-data
              mountPath: /var/www/html
            - name: drupal-data-files
              mountPath: /app/data/docroot/sites/default/files
          envFrom:
            - secretRef:
                name: regcred
          env:
            - name: CLIENTID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DRUPAL_DATABASE_HOST
              value: mariadb
            - name: DRUPAL_DATABASE_NAME
              value: drupal
            - name: DRUPAL_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: drupal-secret
                  key: DRUPAL_DATABASE_USERNAME
            - name: DRUPAL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-secret
                  key: DRUPAL_DATABASE_PASSWORD
            - name: DRUPAL_DATABASE_PORT
              value: "3306"
            - name: DRUPAL_HASH_SALT
              value: fe918c992fb1bcfa01f32303c8b21f3d0a0
          ports:
            - containerPort: 9000
              name: fastcgi
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: drupal-data
          emptyDir: {}
        - name: drupal-data-files
          persistentVolumeClaim:
            claimName: drupal-data-files
        - name: nginx-config-volume
          configMap:
            name: nginx-config
