rbac:
  create: true
 
controller:
  publishService:
    enabled: true
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "true"
  service:
    annotations:
      loadbalancer.openstack.org/proxy-protocol: "true"
      loadbalancer.openstack.org/keep-floatingip: "true" # Reserviert die FloatingIP in OpenStack, auch nach Löschung des HelmCharts bleibt die IP reserviert
      loadBalancerIP: 78.138.66.216 # Hiermit kann eine bereits reservierte FloatingIP definiert werden

